[package]
name = "ezk-sdp-types"
version = "0.5.0"
description = "SDP types providing parsing & serialization"
categories = ["network-programming", "multimedia"]
keywords = ["sdp"]
readme = "README.md"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
internal.workspace = true

bytesstr = "1"
nom = "7"
bytes = "1"
thiserror = "2"
