name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: EmbarkStudios/cargo-deny-action@v2

  cargo-clippy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cargo clippy --all-features --workspace

  cargo-test:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - run: cargo test --all-features --workspace
