name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    
    - uses: actions/checkout@v2
    - name: clippy
      run: cargo clippy --workspace --all-features --tests
    - name: test
      run: cargo test --workspace --all-features
