name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  cargo-deny:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: EmbarkStudios/cargo-deny-action@v2

  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: clippy
      run: cargo clippy --workspace --all-features --tests
    - name: test
      run: cargo test --workspace --all-features
